# Site settings
description: AppPotのブログです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.apppot.jp" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: AppPot Blogs
user_description: NCデザイン＆コンサルティング
user_title: NCデザイン＆コンサルティング
email: info@ncdc.co.jp
twitter_username: app_pot
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
# disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: AppPot Blogトップ
    url: /
  - title: カテゴリ
    url: /series
  - title: タグ
    url: /tags

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
